services:
  api:
    build:
      context: ./backend
    container_name: fastapi-application
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    volumes:
      - ./backend/app:/app
    restart: "no"
    working_dir: /app
    
  web:
    build:
      context: frontend/angular
      target: dev-envs
    ports:
      - 4200:4200
    volumes:
      - ./frontend/angular:/project
      - ./frontend/angular/node_modules:/project/node_modules
      