@baseApiUrl = http://localhost:8000
@email=user@com.pl
@password=custom_password

@username=usercom

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyY29tIiwiZXhwIjoxNzE1NzAxOTkzfQ.L4rXsQ2vm7ZDtR1LD9RKo5RsLBMMMcD2dgfRSIp3oHg


### Login - generate access token
POST {{baseApiUrl}}/api/login HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded

password={{password}}&username={{username}}


### Register user (create)
POST {{baseApiUrl}}/api/register HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "email": "user2@com.pl",
    "username": "usercom",
    "password": "custom_password"
}

### Get possible currencies rates 
GET {{baseApiUrl}}/api/currencies
Authorization: Bearer {{token}}


### Get rates
GET {{baseApiUrl}}/api/rates/USD?date_from=2002-01-01
Authorization: Bearer {{token}}


### Bad request - Register user (create)
POST {{baseApiUrl}}/api/register HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "email": "user2@com.pl",
    "username": "usercom"
}

### Login - generate access token
POST {{baseApiUrl}}/api/login HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded

password={{password}}&username={{username}}

